-- drop table customer;
CREATE TABLE customer (
    id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR2(100),
    last_name    VARCHAR2(200),
    email   VARCHAR2(200),
    phone   VARCHAR2(100)
);
COMMIT;